stages:
  - test
  - package

.docker-template: &docker-template
  tags:
    - docker
  image: $DOCKER_IMAGE
  before_script:
    - apt-get update
    - apt-get install -y python3.8 python3-pip
    - pip install --upgrade pip==21.2.2
    - pip install poetry==1.1.7 nox==2021.6.12

test-docker-ubuntu:20.04:
  stage: test
  variables:
    DOCKER_IMAGE: ubuntu:20.04
  <<: *docker-template
  script:
    - cd template-project
    - nox
    - nox -s docs

release-pypi-test:
  stage: package
  only:
    refs:
      - master
  variables:
    DOCKER_IMAGE: ubuntu:20.04
  <<: *docker-template
  script:
    - cd template-project
    - poetry config repositories.testpypi https://test.pypi.org/legacy/
    - poetry config pypi-token.testpypi $TESTPYPI_TOKEN
    - poetry version $(poetry version | awk '{print $2}').dev.$(date +%Y%m%d+%s)
    - poetry build
    - poetry publish -r testpypi